version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    env_file:
      - ../common/.env
    environment:
      POSTGRES_DB
      POSTGRES_USER
      POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:

  intake-api:
    build:
      context: ..
      dockerfile: ./intake-api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../common/.env
    environment:
      - DATABASE_URL
      - REDIS_URL
      - LLM_ADAPTER
    depends_on:
      - postgres
      - redis

  insights-api:
    build:
      context: ..
      dockerfile: ./insights-api/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ../common/.env
    environment:
      - DATABASE_URL
    depends_on:
      - postgres

  triage-worker:
    build:
      context: ..
      dockerfile: ./triage-worker/Dockerfile
    env_file:
      - ../common/.env
    environment:
      - DATABASE_URL
      - REDIS_URL
      - LLM_ADAPTER
    depends_on:
      - postgres
      - redis

volumes:
  redis_data:
  postgres_data: