from fastapi import FastAPI
from insights_routes import insights_router


app = FastAPI(
    title="Insights API",
    summary="API for retrieving lead insights generated by the triage worker",
)

app.include_router(insights_router)